name: linuxPackages

on:
  release:
    types: [published]

jobs:
  packaging:
    strategy:
      matrix:
        qt_version: [5.14.2]
        platform: [ubuntu-20.04]
        arch: [x64]
      fail-fast: false
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Dependencies
        shell: bash
        run: |
          sudo apt install libgl-dev libx11-dev libxkbcommon-x11-dev

      - name: Installing Qt
        uses: jurplel/install-qt-action@v2.6.2
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Build
        shell: bash
        run: |
          cd scripts
          ./compile.sh

      - name: makeUniversal
        shell: bash
        run: |
          cd scripts
          ./createPackage.sh

      - name: makeDebian
        shell: bash
        run: |
          cd scripts
          ./debian.sh

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: uploadUniversal
        id: universal-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../qTsConverter_universal.zip
          asset_name: "universal package"
          asset_content_type: application/zip

      - name: uploadDebian
        id: debian-asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ../qTsConverter.deb
          asset_name: "debian package"
          asset_content_type: application/vnd.debian.binary-package
