name: linuxPackages

on:
  release:
    types: [published]

jobs:
  packaging:
    strategy:
      matrix:
        qt_version: [5.14.2]
        platform: [ubuntu-20.04]
        arch: [x64]
      fail-fast: false
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Dependencies
        shell: bash
        run: |
          sudo apt install libgl-dev libx11-dev libxkbcommon-x11-dev

      - name: Installing Qt
        uses: jurplel/install-qt-action@v2.6.2
        with:
          version: ${{ matrix.qt_version }}
          arch: ${{ matrix.qtarch }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}

      - name: Build
        shell: bash
        run: |
          cd scripts
          ./compile.sh

      - name: makeUniversal
        shell: bash
        run: |
          cd scripts
          ./createPackage.sh

      - name: makeDebian
        shell: bash
        run: |
          cd scripts
          ./debian.sh

      - name: UploadUniversal
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ../qTsConverter_universal.zip
          asset_name: qTsConverter_universal.zip
          tag: ${{ github.ref }}
          overwrite: true
          body: "linux universal binary release"

      - name: UploadDebian
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ../qTsConverter.deb
          asset_name: qTsConverter.deb
          tag: ${{ github.ref }}
          overwrite: true
          body: "debian package release"
